version: '3.9'
services:
  wppconnect:
    container_name: wppconnect-server
    restart: unless-stopped
    build:
      context: .
    volumes:
      - ./tokens:/usr/src/wpp-server/tokens
      - ./userDataDir:/usr/src/wpp-server/userDataDir
    ports:
      - '21465:21465'
    env_file:
      - .env
    networks:
      - vps_shared_network

networks:
  vps_shared_network:
    external: true
