version: '3.9'
services:
  wppconnect:
    container_name: wppconnect-server
    restart: unless-stopped
    build:
      context: .
    volumes:
      - ./config.ts:/app/config.ts
      - ./wppconnect_tokens:/app/tokens
    ports:
      - '21465:21465'
    env_file:
      - .env
    networks:
      - vps_shared_network

networks:
  vps_shared_network:
    name: vps_shared_network
    driver: bridge
