version: "3"

services:
  wppconnect:
    container_name: wpp-server
    restart: unless-stopped
    environment:
      - PORT=21465
      - CREATE_CLIENT=true
      - WEBHOOK_ENABLED=true
      - WEBHOOK_URL=https://n8n-production-a71c.up.railway.app/webhook/whatsapp-in
      - TOKEN_SECRET=123456
      - SECRET_KEY=123456
    build:
      context: .
    volumes:
      - ./config.ts:/usr/src/wpp-server/config.ts
      - ./wppconnect_tokens:/usr/src/wpp-server/tokens
    ports:
      - "21465:21465"

volumes:
  wppconnect_tokens: {}    
