version: "3.9"

services:
  wppconnect:
    image: wppconnect-team/wppconnect-server:latest
    environment:
      - PORT=21465
      - CREATE_CLIENT=true
      - WEBHOOK_ENABLED=true
      - WEBHOOK_URL=https://n8n-production-a71c.up.railway.app/webhook/whatsapp-in
      - TOKEN_SECRET=123456
    ports:
      - "21465:21465"